CREATE TABLE T_AGENTE
(
	Id INT IDENTITY,
	DocumentoId INT NULL,
	EnderecoId INT NULL,
	ContatoInfoId INT NULL,
	PessoaFisicaId INT NULL,
	PessoaJuridicaId INT NULL,
    PRIMARY KEY (Id)
);

CREATE TABLE T_DOCUMENTO
(
	Id INT IDENTITY,
	Numero VARCHAR(15) NOT NULL,
	AgenteId INT,
	PRIMARY KEY (Id),
	FOREIGN KEY (AgenteId) REFERENCES T_AGENTE (Id)
);

CREATE TABLE T_PESSOA_FISICA
(
	Id INT IDENTITY,
	Nome VARCHAR(120) NOT NULL,
	Sobrenome VARCHAR(225) NOT NULL,
	Nascimento DATETIME NOT NULL,
	AgenteId INT,
	PRIMARY KEY (Id),
	FOREIGN KEY (AgenteId) REFERENCES T_AGENTE (Id)
);

CREATE TABLE T_PESSOA_JURIDICA
(
	Id INT IDENTITY,
	RazaoSocial VARCHAR(225) NOT NULL,
	NomeFantasia VARCHAR(225) NOT NULL,
	RepresentanteId INT,
	AgenteId INT,
	PRIMARY KEY (Id),
	FOREIGN KEY (AgenteId) REFERENCES T_AGENTE (Id)
);

CREATE TABLE T_DEPARTAMENTO
(
	Id INT IDENTITY,
	PRIMARY KEY (Id),
	Nome VARCHAR(225),
);

CREATE TABLE T_FUNCIONARIO
(
	Id INT IDENTITY,
	Salario MONEY NOT NULL,
	Admissao DATETIME NOT NULL,
	Demissao DATETIME NULL,
	Ativo BIT,
	InicioExpediente Time,
	TerminoExpediente Time,
	PessoaFisicaId INT,
	DepartamentoId INT,
	PRIMARY KEY (Id),
	FOREIGN KEY (PessoaFisicaId) REFERENCES T_PESSOA_FISICA (Id),
	FOREIGN KEY (DepartamentoId) REFERENCES T_DEPARTAMENTO (Id)
);


CREATE TABLE T_ENDERECO
(
	Id INT IDENTITY,
	Logradouro VARCHAR(150),
	Numero VARCHAR(10),
	Bairro VARCHAR(150),
	Cidade VARCHAR(150),
	PontoReferencia VARCHAR(150),
	Uf CHAR(2),
	IdTipoEndereco INT,
	Cep VARCHAR(10) NOT NULL,
	AgenteId INT,
	PRIMARY KEY (Id),
	FOREIGN KEY (AgenteId) REFERENCES T_AGENTE (Id)
);

CREATE TABLE T_CONTATO_INFO
(
	Id INT IDENTITY,
	Email VARCHAR(50),
	Telefone VARCHAR(50),
	Celular VARCHAR(50),
	AgenteId INT
	PRIMARY KEY (Id),
	FOREIGN KEY (AgenteId) REFERENCES T_AGENTE (Id)
);

ALTER TABLE T_AGENTE ADD CONSTRAINT FK_DOCUMENTO
FOREIGN KEY(DocumentoId) REFERENCES T_DOCUMENTO(Id);

ALTER TABLE T_AGENTE ADD CONSTRAINT FK_ENDERECO
FOREIGN KEY(EnderecoId) REFERENCES T_ENDERECO(Id);

ALTER TABLE T_AGENTE ADD CONSTRAINT FK_CONTATO_INFO
FOREIGN KEY(ContatoInfoId) REFERENCES T_CONTATO_INFO(Id);

ALTER TABLE T_AGENTE ADD CONSTRAINT FK_PF
FOREIGN KEY(PessoaFisicaId) REFERENCES T_PESSOA_FISICA(Id);

ALTER TABLE T_AGENTE ADD CONSTRAINT FK_PJ
FOREIGN KEY(PessoaJuridicaId) REFERENCES T_PESSOA_JURIDICA(Id);

CREATE UNIQUE INDEX idx_agente
ON T_AGENTE(Id);

CREATE UNIQUE INDEX idx_documento
ON T_DOCUMENTO(Id, AgenteId);

CREATE UNIQUE INDEX idx_pessoa_fisica
ON T_PESSOA_FISICA(Id, AgenteId);

CREATE UNIQUE INDEX idx_pessoa_juridica
ON T_PESSOA_JURIDICA(Id, AgenteId);

CREATE UNIQUE INDEX idx_funcionario
ON T_FUNCIONARIO(Id, PessoaFisicaId);

CREATE UNIQUE INDEX idx_departamento
ON T_DEPARTAMENTO(Id);

CREATE UNIQUE INDEX idx_endereco
ON T_ENDERECO(Id,AgenteId);

CREATE UNIQUE INDEX idx_contato_info
ON T_CONTATO_INFO(Id,AgenteId);